version: "3"
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - KEY_ID="rzp_test_AAZSUIplmuGJ7f"
      - KEY_SECRET="yGfOZwNwsoDKGW3npTn5dAlx"
      - PORT=4000
      - EMAIL="info@zistaeducation.com"
      - PASS="INFO@1234info"
      - SENDGRID_API_KEY="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"
      - LOCAL="http://localhost:4000"
      - SERVER="https://signup.zistaeducation.com"
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app